### ISSUE TITLE
Jackson 2.5 released noguava time?

### ISSUE THREAD

**Issue by lordofthejars** [daveclayton/json-patch#27]
Hi Jackson 2.5 has been released with some changes required to use json-path without guava. There is a topic branch on the project, if you are still interested in that move we could finish it.

**Comment by fge** [comment]
Well, since you're here...

I am looking for a new maintainer for this project; I just don't have the time to maintain it anymore, and worse, I do not have the _incentive_ anymore.

Would you be willing to take over?

**Comment by daveclayton** [comment]
Hi @lordofthejars is this still required?  Happy to start discussions R/E implementing this.

**Comment by lordofthejars** [comment]
I don t think so since JSON-P (jsr374) already implements json patch spec

**Comment by daveclayton** [comment]
OK - thanks.  I'll close the issue - let me know if we need to revisit.
